# Generated by Django 4.1.3 on 2022-11-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=100)),
                ('ExpiryTime', models.TimeField(auto_now=True)),
                ('Image', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.foodcategory')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=100)),
                ('OrderTime', models.TimeField(auto_now=True)),
                ('TotalBill', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fooditem')),
            ],
        ),
    ]
