# Generated by Django 4.1.3 on 2022-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fooditem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Image',
            field=models.ImageField(upload_to='../static/img/'),
        ),
    ]
