# Generated by Django 4.1.3 on 2022-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Desc', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=150)),
                ('Subject', models.CharField(max_length=250)),
                ('Message', models.CharField(max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
