# Generated by Django 4.1.3 on 2022-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_about_contact_alter_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Desc',
            field=models.CharField(max_length=1000),
        ),
    ]
