# Generated by Django 4.1.3 on 2022-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_about_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default='abc', max_length=350),
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(default='12345678', max_length=150),
        ),
    ]
