# Generated by Django 4.1.3 on 2022-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order_address_order_name_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
